server {
    listen 443 ssl;
    server_name www.flaging.cn flaging.cn;

    ssl_certificate /certs/www.flaging.cn.pem;
    ssl_certificate_key /certs/www.flaging.cn.key;

    location / {
        proxy_pass http://nestjs:3000; # 转发到 NestJS 容器
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
