name: Deploy to Test Environment

on:
  push:
    branches:
      - test # 当推送到 test 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用 GitHub 托管的虚拟机运行工作流

    steps:
      # 第一步：检出代码（供 GitHub Actions 执行环境使用，非部署服务器）
      - name: Checkout code
        uses: actions/checkout@v3

      # 第二步：设置 SSH 代理
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 第三步：部署到远程服务器
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@8.130.137.5 "
          # 项目目录路径
          PROJECT_DIR=/usr/src/app/runner-demo

          # 检查项目目录是否存在
          if [ ! -d \"\$PROJECT_DIR\" ]; then
            echo '项目目录不存在，正在克隆仓库...'
            git clone --branch test https://github.com/taninsist/runner-demo.git \$PROJECT_DIR
          else
            echo '项目目录已存在，切换到 test 分支并拉取最新代码...'
            cd \$PROJECT_DIR
            git pull --rebase
            git checkout test
            git reset --hard origin/test
          fi

          # 创建或更新 .env.test 文件
          echo 'BASE_API=${{ env.BASE_API }}' > .env.test
          echo 'PORT=${{ env.PORT }}' >> .env.test
          echo 'NODE_ENV=test' >> .env.test
          

          # 切换到项目目录并更新代码
          cd \$PROJECT_DIR
          docker compose down
          docker compose pull
          docker compose up -d
          "
